services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
  
  db:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  

  # frontend: Пример сервиса фронта
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "5500:5500"  # !!! ВНИМАНИЕ: Порт может измениться
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend  # Зависит от сервера (FastAPI)

volumes:
  postgres_data: